// src/components/Search.vue
<template>
    <form class="form">
        <label for="start" class="form__label">Date from</label>
        <input id="start" type="text" class="form__input" />

        <label for="end" class="form__label ml">Date to</label>
        <input id="end" type="text" class="form__input" />
    </form>
</template>

<style lang="scss" scoped>
    .form {
        width: 100%;
        padding: 15px 0;
        background-color: #eaeaea;
        display: flex;
        justify-content: center;
        align-items: center;

        &__input {
            border-radius: 11px;
            border: solid 1px #979797;
            margin-left: 15px;
            width: 100px;
            height: 31px;
        }

        &__label {
            font-size: 13px;
        }

        .ml {
            margin-left: 45px;
        }
    }
</style>

// React-project/src/components/Search/Search.jsx
import React from 'react';
import './Search.scss'

const Search = props => (
    <form className="search-form">
        <label htmlFor="start" className="search-form__label">Date from</label>
        <input id="start" type="date" className="search-form__input start" onChange={props.filter} />
        
        <br className="br" />
        
        <div>
            <label htmlFor="end" className="search-form__label ml">Date to</label>
            <input id="end" type="date" className="search-form__input end" onChange={props.filter} />
        </div>
    </form>
)

export default Search
