// React-project/src/Views/ListRunning.jsx
import React from 'react';
import { connect } from 'react-redux'
import Search from '../components/Search/Search'
import NewRun from '../components/NewRun/NewRun'
import ChangeRunInfo from '../components/ChangeRunInfo/ChangeRunInfo'
import EmptyRunInfo from '../components/EmptyRunInfo/EmptyRunInfo'
import './ListRunning.scss'

const ListRunning = props => (
    <main className="main">
        {
            props.searchComponent ?
                <Search />
            : null
        }
        

        {/* <div 
            class="main-container" 
            v-show="newRunComponent && !editComponent" 
            v-for="(run, id) in currentRuns"
            :key="id" 
        >
            <Card 
                :run="run" 
                :id="id"
            />

            <hr />
        </div> */}

            {
            props.editComponent ?
                <ChangeRunInfo />
            : null
        }

        {
            !props.newRunComponent ?
                <NewRun />
            : null
        }

        {/* {
            !props.currentRuns.length ?
                <EmptyRunInfo />
            :
                <img src="../assets/img/add.svg" alt="" class="main__img" onClick={props.viewNewRun} />
        } */}
    </main>
)

function mapStateToProps(state) {
    return {
        data: state.variables.data
    }
}

function mapDispatchToProps(dispatch) {
    return {
        
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(ListRunning)

// src/views/ListRunning.vue
<template>
    <main class="main">
        <Search v-if="searchComponent" />

        <div class="main-container" v-if="newRunComponent && !editComponent">
            <Card v-for="(run, id) in runs" :key="id" :run="run" :id="id" />
        </div>

        <ChangeRunInfo v-if="editComponent"/>

        <NewRun  v-if="!newRunComponent" />

        <img src="../assets/img/add.svg" alt="" class="main__img" @click="viewNewRun">
    </main>
</template>

<script>
    import Search from '../components/Search'
    import Card from '../components/Card'
    import NewRun from '../components/NewRun'
    import ChangeRunInfo from '../components/ChangeRunInfo'
    import { mapState } from 'vuex'
    import { mapActions } from 'vuex'

    export default {
        components: {
            Search,
            Card,
            NewRun,
            ChangeRunInfo
        },
        computed: {
            ...mapState({
                searchComponent: state => state.searchComponent,
                newRunComponent: state => state.newRunComponent,
                runs: state => state.runs,
                editComponent: state => state.editComponent
            })
        },
        methods: {
            ...mapActions({
                viewNewRun: 'viewNewRun',
                getCurrentPage: 'getCurrentPage'
            })
        },
        mounted() {
            this.getCurrentPage('ListRunning');
        }
    }
</script>

<style lang="scss" scoped>
    .main {

        &-container {
            padding: 50px 0 0 0;
        }

        &__img {
            position: absolute;
            right: 40px;
            bottom: 40px;
        }
    }
</style>
