// React-project/src/components/Card/Card.jsx
import React from 'react';
import { connect } from 'react-redux'
import {edit} from '../../redux/actions/runs';
import './Card.scss'

const Card = props => (
    <div className="container">
        <img src="../../assets/img/run-man.svg" alt="" className="container__img"/>

        <p className="container__description">
            <span>
                {props.run.date}

                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-pencil" viewBox="0 0 16 16" onClick={props.edit}>
                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                </svg>
            </span>

            <br />

            <span>
                <b>Speed</b>: {props.run.speed}
            </span>

            <br />

            <span>
                <b>Distance</b>: {props.run.distance}
            </span>

            <br />

            <span>
                <b>Time</b>: {props.run.time}
            </span>
        </p>
    </div>
)

function mapStateToProps(state) {
    return {
        data: state.variables.data
    }
}

function mapDispatchToProps(dispatch) {
    return {
        edit: () => dispatch(edit())
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(Card)

// src/components/Card.vue
<template>
    <div class="container">
        <img src="../assets/img/run-man.svg" alt="" class="container__img"/>

        <p class="container__description">
            <span>
                {{run.date}}

                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16" @click="edit">
                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                </svg>
            </span>
            <br>
            <span>
                <b>Speed</b>: {{run.speed}}
            </span>
            <br>
            <span>
                <b>Distance</b>: {{run.distance}}
            </span>
            <br>
            <span>
                <b>Time</b>: {{run.time}}
            </span>
        </p>
    </div>
</template>

<script>
    import { mapState } from 'vuex'
    import { mapActions } from 'vuex'

    export default {
        props: [
            'run',
            'id'
        ],
        methods: {
            edit() {
                this.getCurrentRunKey(this.id);
            },
            ...mapActions({
                runKey: 'runKey',
                getCurrentPage: 'getCurrentPage',
                getCurrentRunKey: 'getCurrentRunKey'
            })
        },
        computed: {
            ...mapState({
                searchComponent: state => state.searchComponent,
                newRunComponent: state => state.newRunComponent,
                runs: state => state.runs
            })
        },
    }
</script>

<style lang="scss" scoped>
    .container {
        margin: 0 auto;
        width: 320px;
        display: flex;
        align-items: center;
        margin-bottom: 75px;

        &__description {
            margin-left: 45px;
        }
    }
</style>
