// Vue-project/src/views/LetMeIn.vue
<template>
    <main class="main" :style="{height: mainHeight + 'px'}">
        <div class="main-login">
            <img 
                src="../assets/img/bear-face.svg" 
                alt="bear-face img" 
                class="main-login__img--desctop" 
            />

            <img 
                src="../assets/img/bearFace.png" 
                alt="bear-face img" 
                class="main-login__img--mobile" 
            />

            <router-link to="/Jogs" class="main-login__button">Let me in</router-link>
        </div>
    </main>
</template>

<script>
    import { mapActions } from 'vuex'

    export default {
        data() {
            return {
                mainHeight: null,
                innerWidth: null
            }
        },
        methods: {
            mainHeightResult() {
                let appEl = document.querySelector('#app').clientHeight;
                
                this.mainHeight = appEl - 116;
            },
            ...mapActions({
                getCurrentPage: 'getCurrentPage'
            })
        },
        mounted() {
            this.mainHeightResult();
            this.getCurrentPage('LetMeIn');

            window.onresize = () => {
                this.mainHeightResult();
            };
        }
    }
</script>

<style lang="scss" scoped>
    .main {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;

        &-login {
            margin: auto;
            width: 503px;
            height: 379px;
            border-radius: 44px;
            background-color: #e990f9;
            display: flex;
            flex-direction: column;
            flex-wrap: nowrap;
            align-items: center;

            @media(max-width: 550px) {
                background-color: white;
            }

            &__img {

                @media(max-width: 550px) {
                    width: 160px;
                }

                &--desctop {
                    display: block;
                    margin-top: 77px;

                    @media(max-width: 550px) {
                        display: none;
                    }
                }

                &--mobile {
                    display: none;
                    margin-top: 77px;

                    @media(max-width: 550px) {
                        display: block;
                    }
                }
            }

            &__button {
                margin-top: 56px;
                padding: 20px 34px;
                border-radius: 36px;
                border: solid 3px white;
                color: white;
                background-color: transparent;
                font-size: 18px;
                font-weight: bold;
                text-decoration: none;

                @media(max-width: 550px) {
                    margin-top: 103px;
                    
                    color: rgb(233, 144, 249);
                    border: solid 3px rgb(233, 144, 249);
                }
            }
        }
    }
</style>

// React-project/src/Views/LetMeIn.jsx
import React from 'react';
import { connect } from 'react-redux'
import { NavLink } from 'react-router-dom';
import './LetMeIn.scss'

const LetMeIn = props => (
    <main className="main">
        <div className="main-login">
            <img 
                src="../assets/img/bear-face.svg" 
                alt="bear-face img" 
                className="main-login__img--desctop" 
            />

            <img 
                src="../assets/img/bearFace.png" 
                alt="bear-face img" 
                className="main-login__img--mobile" 
            />

            <NavLink className="main-login__button" to="/Jogs">Let me in</NavLink>
        </div>
    </main>
)

function mapStateToProps(state) {
    return {
        data: state.variables.data
    }
}

function mapDispatchToProps(dispatch) {
    return {
        
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(LetMeIn)
